List<Map<String, dynamic>> ApiResponse = [
    {
      "id": 1,
      "name": "Ahmed ",
      "message": "Hey, how are you?",
      "time": "5:30 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTLKAW1zadB8CAjYC63Z-ZghmLs-VWb5D9QMqs1WxFnS1SYR3WeZSJEoE&s",
      "message_type": "text",
    },
    {
      "id": 2,
      "name": "Omar",
      "message": "See you tomorrow 👍",
      "time": "4:45 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdRAAafrq3uDXl0Ldruo13jSzxtE5K5hTsk54Ub8d2cqhEo6YlfJIMl04&s",
      "message_type": "text",
    },
    {
      "id": 3,
      "name": "Khaled",
      "message": "Send me the file please",
      "time": "3:20 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5qINl9tvmE47DFcINThBLve6-vYVb4-gw9U-N0VqVtQ&s=10" ,
      "message_type": "text",
    },
    {
      "id": 4,
      "name": "Youssef ",
      "message": "😂😂",
      "time": "2:15 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUMy4sj63vuL3oSiolmH_4JnF6IJcJAHpJWwSJyGgcfGyzLlKskK60nmI&s",
      "message_type": "emoji",
    },
    {
      "id": 5,
      "name": "Mostafa",
      "message": "can you help me",
      "time": "1:40 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRudhNOBtEaervywZAm0x0E1GsDjSD74XxlN0dBRNkYGK6K0qNEBf39ciU&s",
      "message_type": "text",
    },
    {
      "id": 6,
      "name": "Mahmoud",
      "message": "Can you send me the project file when you have time?",
      "time": "12:30 PM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7fkW2aeAIJJgXKT6c50dtcNp5q-emzSIvlvbbPMiano541-6IWqP-Nes&s",
      "message_type": "text",
    },
    {
      "id": 7,
      "name": "Sara ",
      "message": "Thank you ❤️",
      "time": "11:20 AM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxqQ4omtiB38H7HQ7W7_-hED2OGcKdMbTrOTfRgdl1Tg&s=10",
      "message_type": "text",
    },
    {
      "id": 8,
      "name": "Mariam",
      "message": "Good morning 🌸",
      "time": "10:15 AM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKDrID6GlSHW5NdLTZvCdOQ7TCQ17eCkXknEUMsaj3zQ&s=10",
      "message_type": "text",
    },
    {
      "id": 9,
      "name": "Ibrahim",
      "message": "We need to finish the project before the deadline.",
      "time": "9:45 AM",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt-GU43EU9opz_7t9eTm501aaJlMxxoDXCJoLE2-RvU2WLESmez1Mx9iI&s",
      "message_type": "text",
    },
    {
      "id": 10,
      "name": "Hassan",
      "message": "Let's meet at 7",
      "time": "Yesterday",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3aPrthlurDAJmoZZ1d640nR79WPyveyWtMgzEuNqArNTFAUD44nVUOuk&s",
      "message_type": "text",
    },
    {
      "id": 11,
      "name": "Ali ",
      "message": "gif",
      "time": "Yesterday",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJROZNHq-BYqY-c1ZEGPpLUW5aBiBcorOzRsnF1ULVJQ&s",
      "message_type": "gif",
    },
    {
      "id": 12,
      "name": "Amr",
      "message": "video",
      "time": "Yesterday",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmNNZ1pyYAzRJAIqBWyYSamjYRfJHEQc7aDnfsVUcgQQ&s",
      "message_type": "video",
    },
  ];
